[package]
name = "serial-com"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#serialport = "3.3.0"
serialport = { path = "./packages/serialport-rs" }
structopt = "0.3.25"
